---
language: node_js
node_js:
  - "6"
os: osx

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g npm@^3
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm --version
  - ember --version
  - npm run test-main
  - ember electron:test
  - ember electron:package
