version: 0.0.{build}

skip_non_tags: true

build:
    verbosity: minimal

platform:
  - x64

cache:
  - node_modules --> package.json
  - bower_components -> bower.json

install:
  - ps: Install-Product node 6 $env:PLATFORM
  - npm install bower -g
  - npm install npm -g
  - npm install
  - bower install

build_script:
  - node --version
  - node node_modules\ember-cli\bin\ember electron:package --platform win32

after_build:
  - cd electron-builds
  - 7z a dummy-win32-ia32.zip dummy-win32-ia32
  - 7z a dummy-win32-x64.zip dummy-win32-x64
  - cd ..
  - ps: ls electron-builds

artifacts:
  - path: 'electron-builds\*.zip'
    name: electron-package

test: off

deploy:
  provider: GitHub
  auth_token:
    secure: b4fa65a50a3f05fb63b6aec706ea3f8f3f9315cf
  artifact: electron-package
  on:
    appveyor_repo_tag: true
