version: 0.0.{build}

skip_non_tags: true

build:
    verbosity: minimal

platform:
  - x64

cache:
  - node_modules
  - bower_components
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 6 x64
  - npm install bower -g
  - npm install
  - bower install

build_script:
  - node --version
  - node node_modules\ember-cli\bin\ember electron:package --platform win32

after_build:
  - 7z a electron-builds\%eu_package_name% electron-builds\dummy-win32-ia32
  - 7z a electron-builds\%eu_package_name% electron-builds\dummy-win32-x64
  - ps: ls electron-builds

artifacts:
  - path: 'electron-builds\*.zip'
    name: electron-package

test: off
